import transporter, { mailSender } from "./emailConfig.js";

export const sendMomNotification = async (
  meeting,
  participants = []
) => {
  console.log(
    `📧 Triggering MOM email service for meeting: ${meeting.title}`
  );

  const recipients = participants.filter(
    (p) => p.email && p.email.trim() !== ""
  );

  for (const participant of recipients) {
    try {
      const actionItems =
        meeting.actionItems?.length > 0
          ? meeting.actionItems
              .map(
                (item, index) =>
                  `${index + 1}. ${item.description}`
              )
              .join("\n")
          : "No action items recorded.";

      const html = `
        <h2>Minutes of Meeting (MOM)</h2>

        <p><strong>Meeting:</strong> ${meeting.title}</p>
        <p><strong>Date:</strong> ${meeting.date}</p>
        <p><strong>Venue:</strong> ${meeting.venue}</p>

        <h3>Action Items</h3>
        <pre>${actionItems}</pre>

        <p>
          This is an automated MOM generated by the
          Radiation Safety Management System.
        </p>
      `;

      await transporter.sendMail({
        from: `"RSO Safety Admin" <${mailSender}>`,
        to: participant.email,
        subject: `MOM - ${meeting.title}`,
        html,
      });

      console.log(
        `✅ MOM sent successfully to ${participant.email}`
      );
    } catch (error) {
      console.error(
        `❌ MOM send failed for ${participant.email}`,
        error
      );
    }
  }

  return true;
};